version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: test12345
      MYSQL_DATABASE: fastapi
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init_sql.sql:/docker-entrypoint-initdb.d/init_sql.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql+aiomysql://fastapi_user:test12345@db/fastapi
    ports:
      - "80:80"
    depends_on:
      - db