apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./k8s
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out ./k8s
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/secure-fastapi-template-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: fastapi
            - name: POSTGRES_PASSWORD
              value: test12345
            - name: POSTGRES_USER
              value: fastapi_user
          image: postgres:13
          livenessProbe:
            exec:
              command:
                - pg_isready -U fastapi_user -d fastapi
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: postgres-db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init_sql.sql
              name: db-cm0
              subPath: init_sql.sql
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init_sql.sql
                path: init_sql.sql
            name: db-cm0
          name: db-cm0
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
