apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/secure-fastapi-template-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: fastapi
            - name: MYSQL_PASSWORD
              value: test12345
            - name: MYSQL_ROOT_PASSWORD
              value: root12345
            - name: MYSQL_USER
              value: fastapi_user
          image: mysql:8.0
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 10
            timeoutSeconds: 20
          name: db
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init_sql.sql
              name: db-cm0
              subPath: init_sql.sql
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init_sql.sql
                path: init_sql.sql
            name: db-cm0
          name: db-cm0
